# Generated by Django 3.0.5 on 2020-07-07 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(validators=[django.core.validators.MinLengthValidator(2)])),
                ('url', models.URLField(validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
